# This docker-compose config for ArchiveBox runs the following containers:
#     - ArchiveBox (it creates the initial archive, then sleeps forever to allow commands to be run with exec to add links)
#     - nginx webserver running on https://127.0.0.1:8098
# Usage:
#     docker-compose up -d
#     echo "https://example.com" | docker-compose exec -T archivebox /bin/archive
#     docker-compose exec archivebox /bin/archive https://example.com/some/feed.rss
# Documentation:
#     https://github.com/pirate/ArchiveBox/wiki/Docker#docker-compose

version: "3.7"

services:
  archivebox:
    image: 'nikisweeting/archivebox'
    container_name: 'archivebox'
    hostname: 'archivebox'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stdin_open: true                           # needed to be able to input URLs directly after `docker-compose up`
    tty: true                                  # needed to be able to pipe in URLs via stdin to `docker-compose exec ...`
    volumes:
      - type: bind
        source: "./data/archivebox"
        target: "/data"
    env_file:
      - 'etc/archivebox/archivebox.conf'       # this feature is available starting >v0.4
    environment:
      TZ: "Asia/Shanghai"
      USE_COLOR: "False"                       # make docker logs nicer by not spamming lots of ANSI colors
      SHOW_PROGRESS: "False"                   # make docker logs nicer by not writing lots of progress bar lines
    # command: bash -c 'echo "https://github.com/pirate/ArchiveBox" | /bin/archive; tail -f /dev/null'  # archive the Github repo homepage as a starting point so the index doesn't just show an empty list to new users

  archivebox-nginx:
    image: 'nginx:1.17.10'
    container_name: 'archivebox-nginx'
    hostname: 'archivebox-nginx'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - "traefik"
    volumes:
      - type: bind
        source: "./etc/nginx/nginx.conf"
        target: "/etc/nginx/nginx.conf"
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: "./data/archivebox"
        target: "/data"
        read_only: true
        volume:
          nocopy: true
    environment:
      TZ: "Asia/Shanghai"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.archivebox-https.rule=Host(`archivebox.issenn.cf`)"
      - "traefik.http.routers.archivebox-https.entrypoints=websecure"
      - "traefik.http.routers.archivebox-https.tls=true"
      - "traefik.http.routers.archivebox-https.tls.certresolver=test"
      - "traefik.http.routers.archivebox-https.service=archivebox"
      - "traefik.http.routers.archivebox-http.rule=Host(`archivebox.issenn.cf`)"
      - "traefik.http.routers.archivebox-http.entrypoints=web"
      - "traefik.http.routers.archivebox-http.middlewares=https-redirect"
      - "traefik.http.routers.archivebox-http.service=archivebox"
      - "traefik.http.services.archivebox.loadbalancer.server.port=80"

# you can also use named volumes / network volumes if you prefer them to simple local mounts
# volumes:
#     archivebox-data:
#     archivebox-config:
#     etc. a full example will be added after the v0.4 release

# 先创建外部网卡
# docker network create traefik
networks:
  # default:
  #   # driver: bridge
  #   external: true
  traefik:
    name: "traefik"
    # driver: "bridge"
    external: true
